<? return array (
  'name' => 'eshop_order',
  'parent' => '',
  'fields' => 
  array (
    0 => 
    array (
      'id' => 'lst8eiqme0tfvsqpastyurdf50dmuh',
      'name' => 'id',
      'type' => 'jft7-kef8-ccd6-kg85-iueh',
      'editable' => '2',
      'label' => 'Номер заказа',
      'group' => 'Основное',
      'default' => '',
      'indexEnabled' => '0',
      'help' => '',
    ),
    1 => 
    array (
      'id' => 'qp5iqy5zxwesq41rd8as7w12tc9bdp',
      'name' => 'sent',
      'type' => 'x8g2-xkgh-jc52-tpe2-jcgb',
      'editable' => '2',
      'label' => 'Заказ отправлен',
      'group' => 'Основное',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    2 => 
    array (
      'id' => 'pv6j81sn4ls7f90xw903merocu23ce',
      'name' => 'name',
      'type' => 'v324-89xr-24nk-0z30-r243',
      'editable' => '1',
      'label' => 'Имя клиента',
      'group' => 'Основное',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'length' => '',
    ),
    3 => 
    array (
      'id' => 'stm56xkestpv2t4ezom1rdp9itp5s7',
      'name' => 'phone',
      'type' => 'v324-89xr-24nk-0z30-r243',
      'editable' => '1',
      'label' => 'телефон',
      'group' => 'Основное',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'length' => '',
    ),
    4 => 
    array (
      'id' => 'c9z741zdyv0okgb3p10dyvztc12jke',
      'name' => 'email',
      'type' => 'v324-89xr-24nk-0z30-r243',
      'editable' => '1',
      'label' => 'Адрес электронной почты',
      'group' => 'Основное',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'length' => '',
    ),
    5 => 
    array (
      'id' => 'erjflrnmusdyaztmlhdkgsqpe6ncab',
      'name' => 'comments',
      'type' => 'kbd4-xo34-tnb3-4nxl-cmhu',
      'editable' => '1',
      'label' => 'Комментарии к заказу',
      'group' => 'Основное',
      'default' => '',
      'indexEnabled' => '0',
      'help' => '',
    ),
    6 => 
    array (
      'id' => 'wit79cnuwkd9s1ehdrki36x9guzu2a',
      'name' => 'postcode',
      'type' => 'v324-89xr-24nk-0z30-r243',
      'editable' => '1',
      'label' => 'Почтовый индекс',
      'group' => 'Доставка',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'length' => '',
    ),
    7 => 
    array (
      'id' => '453dj8ldo291liqyzxoymrmhe0klsv',
      'name' => 'city',
      'type' => 'v324-89xr-24nk-0z30-r243',
      'editable' => '1',
      'label' => 'Город',
      'group' => 'Доставка',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'length' => '',
    ),
    8 => 
    array (
      'id' => '8pr5utc9qo07op3ntbc6tmcl9dsf2t',
      'name' => 'country',
      'type' => 'v324-89xr-24nk-0z30-r243',
      'editable' => '1',
      'label' => 'Страна',
      'group' => 'Доставка',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'length' => '',
    ),
    9 => 
    array (
      'id' => 'hlfutsiz2xwcwwcde5dhzqp3q9xd6q',
      'name' => 'street',
      'type' => 'v324-89xr-24nk-0z30-r243',
      'editable' => '1',
      'label' => 'Улица',
      'group' => 'Доставка',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'length' => '',
    ),
    10 => 
    array (
      'id' => '0zrw9rqsmvf3kr9mxmxwu6n7x57y9y',
      'name' => 'house',
      'type' => 'v324-89xr-24nk-0z30-r243',
      'editable' => '1',
      'label' => 'Дом',
      'group' => 'Доставка',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'length' => '',
    ),
    11 => 
    array (
      'id' => 'evslw8ry6k13f3t0v3psgnf1l6b3sv',
      'name' => 'building',
      'type' => 'v324-89xr-24nk-0z30-r243',
      'editable' => '1',
      'label' => 'Строение',
      'group' => 'Доставка',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'length' => '',
    ),
    12 => 
    array (
      'id' => 'sp3d328vu8eztihrfblftkkbiwvk15',
      'name' => 'flat',
      'type' => 'v324-89xr-24nk-0z30-r243',
      'editable' => '1',
      'label' => 'Квартира/офис',
      'group' => 'Доставка',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'length' => '',
    ),
    13 => 
    array (
      'id' => 'rqwuin896qmustwezo850781idcgb7',
      'name' => 'userID',
      'type' => 'pg03-cv07-y16t-kli7-fe6x',
      'editable' => '2',
      'label' => 'Пользователь',
      'group' => 'Дополнительно',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'class' => 'user',
      'collection' => '',
      'titleMethod' => '',
    ),
    14 => 
    array (
      'id' => 'cqwnh0udw28ju4uo8f1sdmfig7xese',
      'name' => 'status',
      'type' => 'v324-89xr-24nk-0z30-r243',
      'editable' => '2',
      'label' => 'Сатус заказа',
      'group' => 'Дополнительно',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'length' => '',
    ),
    15 => 
    array (
      'id' => 'okuh3kl2xcl0345zxwlidpuin4vzdm',
      'name' => 'total',
      'type' => 'nmu2-78a6-tcl6-owus-t4vb',
      'editable' => '2',
      'label' => 'Общая сумма',
      'group' => 'Дополнительно',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    16 => 
    array (
      'id' => 'd85rnmein850nku07f96nm10jmgidw',
      'name' => 'security',
      'type' => 'v324-89xr-24nk-0z30-r243',
      'editable' => '0',
      'label' => 'security code',
      'group' => 'Дополнительно',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'length' => '',
    ),
    17 => 
    array (
      'id' => 'sxfe6qmv2qplzo4g6xkasnm5zn8v6q',
      'name' => 'created',
      'type' => 'x8g2-xkgh-jc52-tpe2-jcgb',
      'editable' => '2',
      'label' => 'Дата создания',
      'group' => 'Дополнительно',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    18 => 
    array (
      'id' => '2jces34e678uhx8e0d8lzj8vsj41sd',
      'name' => 'changed',
      'type' => 'x8g2-xkgh-jc52-tpe2-jcgb',
      'editable' => '2',
      'label' => 'Дата изменения',
      'group' => 'Дополнительно',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    19 => 
    array (
      'id' => 'f927wl0n410x4grxpg0opli3cgixca',
      'name' => 'session',
      'type' => 'pg03-cv07-y16t-kli7-fe6x',
      'editable' => '0',
      'label' => 'Сессия',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'class' => 'stat_session',
      'collection' => '',
      'titleMethod' => '',
    ),
  ),
  'indexes' => 
  array (
  ),
); ?>