<? return array (
  'name' => 'realty_flat',
  'parent' => '',
  'fields' => 
  array (
    0 => 
    array (
      'id' => '816qwvztkebok1ht8vb3cu23w5rtp5',
      'name' => 'id',
      'type' => 'jft7-kef8-ccd6-kg85-iueh',
      'editable' => '0',
      'label' => '',
      'group' => '',
      'default' => '',
      'indexEnabled' => '0',
      'help' => '',
    ),
    1 => 
    array (
      'id' => 'f50tpvh3plho8u63cgrnpe2jwuht89',
      'name' => 'location',
      'type' => 'pg03-cv07-y16t-kli7-fe6x',
      'editable' => '1',
      'label' => 'Местоположение',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'class' => '',
      'collection' => '',
      'titleMethod' => '',
    ),
    2 => 
    array (
      'id' => 'jy16q8ahjmvzjpgstyu6n8arnyesdf',
      'name' => 'descr',
      'type' => 'kbd4-xo34-tnb3-4nxl-cmhu',
      'editable' => '1',
      'label' => 'Описание',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    3 => 
    array (
      'id' => 'pahd89zxc5rnyubn4vbt816qwvztke',
      'name' => 'photos',
      'type' => 'f927-wl0n-410x-4grx-pg0o',
      'editable' => '1',
      'label' => 'Фотографии',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    4 => 
    array (
      'id' => '7c16t4ah741rnpgrq4ehnkusnc9sxy',
      'name' => 'type',
      'type' => 'pg03-cv07-y16t-kli7-fe6x',
      'editable' => '1',
      'label' => 'Тип помещения',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'class' => '',
      'collection' => '',
      'titleMethod' => '',
    ),
    5 => 
    array (
      'id' => 'itkas78uztyehoy5bdpe27p5iqp1zt',
      'name' => 'houseType',
      'type' => 'pg03-cv07-y16t-kli7-fe6x',
      'editable' => '1',
      'label' => 'Тип дома',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'class' => '',
      'collection' => '',
      'titleMethod' => '',
    ),
    6 => 
    array (
      'id' => 'kv0omvi3m9h7fuh38ub3m16tp9stmu',
      'name' => 'totalArea',
      'type' => 'yvbj-cgin-m90o-cez7-mv2j',
      'editable' => '1',
      'label' => 'Общая площадь (м2)',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    7 => 
    array (
      'id' => '8erjmvzny12xpl2qy1z7ceztylr7f1',
      'name' => 'livingArea',
      'type' => 'yvbj-cgin-m90o-cez7-mv2j',
      'editable' => '1',
      'label' => 'Жилая площадь (м2)',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    8 => 
    array (
      'id' => '2qy1b34v0nkart8gbqm1iofuijpaix',
      'name' => 'kitchenArea',
      'type' => 'yvbj-cgin-m90o-cez7-mv2j',
      'editable' => '1',
      'label' => 'Площадь кухни (м2)',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    9 => 
    array (
      'id' => 'rqclbj416x89r3fl2ow9hdm90j8lz3',
      'name' => 'price',
      'type' => 'nmu2-78a6-tcl6-owus-t4vb',
      'editable' => '1',
      'label' => 'Стоимость (руб.)',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    10 => 
    array (
      'id' => '5bokv678u2xke6jcg6789rt8uinka0',
      'name' => 'state',
      'type' => 'fahq-we67-klh3-456t-plbo',
      'editable' => '1',
      'label' => 'Состояние',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'list' => '',
      'method' => '',
    ),
    11 => 
    array (
      'id' => 'r7yvbny10dcahtkub38uitm92n81b7',
      'name' => 'floorsTotal',
      'type' => 'gklv-0ijh-uh7g-7fhu-4jtg',
      'editable' => '1',
      'label' => 'Этажность дома',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    12 => 
    array (
      'id' => '4ehnm5zqkv6np1inwl0tmaz7kg27mu',
      'name' => 'floor',
      'type' => 'gklv-0ijh-uh7g-7fhu-4jtg',
      'editable' => '1',
      'label' => 'Этаж помещения',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    13 => 
    array (
      'id' => 'nm5b3mgsxk5sdf9ixyvhx8uzx89h7w',
      'name' => 'balcony',
      'type' => 'fsxp-lhdw-ghof-1rnk-5bqp',
      'editable' => '1',
      'label' => 'Балкон',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    14 => 
    array (
      'id' => '1i3k923y5h7pe6nmubdmahofu2xm16',
      'name' => 'phone',
      'type' => 'fsxp-lhdw-ghof-1rnk-5bqp',
      'editable' => '1',
      'label' => 'Телефон',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    15 => 
    array (
      'id' => 'sx4v67cerdwlhokuh3kl2xcl0345zx',
      'name' => 'internet',
      'type' => 'fsxp-lhdw-ghof-1rnk-5bqp',
      'editable' => '1',
      'label' => 'Интернет',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
    ),
    16 => 
    array (
      'id' => 'oklrn816tf9i78uhj45h7yuzjm5b74',
      'name' => 'roomState',
      'type' => 'v324-89xr-24nk-0z30-r243',
      'editable' => '1',
      'label' => 'Состояние помещения',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'length' => '',
    ),
    17 => 
    array (
      'id' => 'h7p5rdy1zqkgztklzqwestc9r34lhq',
      'name' => 'bathroom',
      'type' => 'fahq-we67-klh3-456t-plbo',
      'editable' => '1',
      'label' => 'Санузел',
      'group' => '',
      'default' => '',
      'indexEnabled' => '1',
      'help' => '',
      'list' => '',
      'method' => '',
    ),
  ),
  'indexes' => 
  array (
  ),
); ?>